baseurl = "https://seb.deleuze.fr"
title = "seb.deleuze.fr"
theme = "coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  author = "Sébastien Deleuze"
  info = "Spring Framework core committer, WebAssembly believer since 2016, Kotlin and ex Dart Google Developer Expert."
  description = "Sébastien Deleuze's personal website"
  keywords = "blog,developer,spring,kotlin,webassembly"
  avatarurl = "images/profil.jpg"
  license = "Creative Commons <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\" target=\"_blank\">BY-SA 4.0</a>"
  since = 2022

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = false

  customCSS = []
  customSCSS = []
  customJS = []

  mainSections = [ "posts" ]

[params.goatCounter]
  code = "sdeleuze"

[taxonomies]
  tag = "tags"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/sdeleuze"
  target="_blank"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://mastodon.online/@sdeleuze"
  rel = "me"
  target="_blank"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/sdeleuze"
  target="_blank"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/deleuze"
    target="_blank"
[[params.social]]
  name = "RSS"
  icon = "fa fa-2x fa-rss"
  weight = 6
  url = "/index.xml"
  rel = "alternate"
  type = "application/rss+xml"

[permalinks]
  posts = "/:filename/"

[[menu.main]]
name = "Posts"
weight = 1
url  = "posts/"

[[menu.main]]
name = "Presentations"
weight = 2
url  = "presentations/"

[[menu.main]]
name = "Podcasts"
weight = 3
url  = "podcasts/"
